import { useGLTF } from "@react-three/drei";
import { useConfig } from "@store";
import extend from "just-extend";
import { useControls } from "leva";

const config = {
  "model": "stove.glb",
  "512": "/stove/512",
  "quality": "512"
};

export function Stove(props) {
  const stove = useConfig(e => e.Stove);
  const { nodes, materials } = useGLTF(
    `${config[config.quality]}/${config.model}`
  );
  const stoveProps = useControls("Stove", extend(true, stove, {}), {
    collapsed: true
  });
  return (
    <group {...props} position={[0, 0, 0]} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stoveBase_1["geometry"]}
          material={materials.stoveBase_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stoveTop_1["geometry"]}
          material={materials.stoveTop_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.exhaust_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.burner01_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.burner02_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.burner03_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.burner04_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tr_prong1_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tr_prong2_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tr_prong3_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tr_prong4_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tr_base_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.br_prong1_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.br_prong2_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.br_prong3_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.br_prong4_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.br_base_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tl_prong1_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tl_prong2_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tl_prong3_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tl_prong4_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tl_base_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bl_prong1_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bl_prong2_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bl_prong3_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bl_prong4_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bl_base_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stovePanel_1["geometry"]}
          material={materials.sectionMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.c_knob_1["geometry"]}
          material={materials.knobs_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.c_knobAttachment_1["geometry"]}
          material={materials.knobs_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mr_knob_1["geometry"]}
          material={materials.knobs_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mr_knobAttachment_1["geometry"]}
          material={materials.knobs_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.r_knob_1["geometry"]}
          material={materials.knobs_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.r_knobAttachment_1["geometry"]}
          material={materials.knobs_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.l_knob_1["geometry"]}
          material={materials.knobs_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.l_knobAttachment_1["geometry"]}
          material={materials.knobs_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ml_knob_1["geometry"]}
          material={materials.knobs_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ml_knobAttachment_1["geometry"]}
          material={materials.knobs_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.button_1["geometry"]}
          material={materials.knobs_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.buttonCasing_1["geometry"]}
          material={materials.knobs_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stoveDoor_1["geometry"]}
          material={materials.stoveDoor_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.innerDoor_1["geometry"]}
          material={materials.doorGlass_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.outterGlass_1["geometry"]}
          material={materials.doorGlass_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.innerGlass_1["geometry"]}
          material={materials.doorGlass_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.attachment1_1["geometry"]}
          material={materials.sectionMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.attachment2_1["geometry"]}
          material={materials.sectionMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.handle_1["geometry"]}
          material={materials.sectionMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stoveDrawer_1["geometry"]}
          material={materials.sectionMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lowerHandle_1["geometry"]}
          material={materials.sectionMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stoveFoot01_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stoveFoot02_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stoveFoot03_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stoveFoot04_1["geometry"]}
          material={materials.grateMetals_mtl_1001}
        />
      </group>
    </group>
  );
}
